/* Guided presentation only. This file contains prepared examples and simple
   walkthrough state; it does not contain or call the application engines. */
'use strict';
const $ = (selector) => document.querySelector(selector);
const params = new URLSearchParams(location.search);
const role = ['admin', 'guard', 'customer'].includes(params.get('role')) ? params.get('role') : 'admin';
const names = { admin: 'Office', guard: 'Guard', customer: 'Customer' };
const key = 'keystone_guided_walkthrough_v1';
let state = { finding: 'open', published: 'open', compared: false };
try { const saved = JSON.parse(localStorage.getItem(key)); if (saved && ['open','checked','repaired','closed'].includes(saved.finding) && ['open','checked','repaired','closed'].includes(saved.published)) state = { ...state, ...saved }; } catch { /* Storage is optional. */ }
let scenario = 'absence', opportunity = 'nearby', highlight = false;
const allowed = role === 'admin' ? ['intelligence','memory','plan-b','growth','change-watch'] : role === 'guard' ? ['patrol','memory','change-watch'] : ['home','memory'];
const labels = { intelligence:'Intelligence', memory:'Site Memory', 'plan-b':'Plan B', growth:'Growth Radar', 'change-watch':'Change Watch', patrol:'Today’s patrol', home:'Your property' };
function path(view, persona = role) { return `./?role=${persona}#/${view}`; }
function viewName() {
  const raw = location.hash.slice(1).split('?')[0].split('/').filter(Boolean).pop();
  return allowed.includes(raw) ? raw : allowed[0];
}
function persist() { try { localStorage.setItem(key, JSON.stringify(state)); } catch { /* Continue in memory. */ } }
let noticeTimer;
function notice(message) { $('#notice').textContent = message; clearTimeout(noticeTimer); noticeTimer = setTimeout(() => { $('#notice').textContent = ''; }, 6500); }
function heading(eyebrow, title, sub) { return `<div class="intro"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${sub}</p></div>`; }
function action(label, id, secondary = false) { return `<button class="button${secondary ? ' secondary' : ''}" data-action="${id}">${label}</button>`; }
function link(label, view, persona = role) { return `<a class="button secondary" href="${path(view, persona)}">${label} →</a>`; }
function stats(items) { return `<div class="stats">${items.map(([number,label])=>`<div class="stat"><b>${number}</b><span>${label}</span></div>`).join('')}</div>`; }
function home() {
  return heading('BUILT FOR KEYSTONE', 'Keystone Intelligence', 'Know each property. Test the plan. Grow with confidence.') + `<section class="hero"><p class="eyebrow">FROM EVIDENCE TO BETTER DECISIONS</p><h2>Every patrol adds knowledge.<br>Every plan has a reason.</h2><p>Explore four connected ideas. Follow a sample finding from the guard’s next check to the customer’s reviewed update, then explore prepared operational and commercial scenarios.</p></section><div class="grid">${[
    ['memory','◈','CARRY KNOWLEDGE FORWARD','Site Memory','Keep a property’s weak points in view, follow recurring issues and review evidence of repair.','Open the site history'],
    ['plan-b','↻','REHEARSE TONIGHT','Plan B','Explore how an absent guard, a failed vehicle or simultaneous call-outs could affect the operation.','Explore prepared scenarios'],
    ['growth','◎','MAKE THE NEXT CONTRACT FIT','Growth Radar','Compare example opportunities by extra travel, service costs and remaining capacity.','Compare sample opportunities'],
    ['change-watch','▧','SEE WHAT HAS CHANGED','Change Watch','See how a reference image and a new inspection can help an officer record a change.','Open the inspection example']
  ].map(([view,icon,eyebrow,title,body,cta])=>`<a class="card feature" href="${path(view)}"><span class="glyph" aria-hidden="true">${icon}</span><p class="eyebrow">${eyebrow}</p><h2>${title}</h2><p>${body}</p><span class="go">${cta} →</span></a>`).join('')}</div>`;
}
function statusFor(value) { return {open:['Needs attention','The side gate latch has worked loose again. A permanent repair is needed.'],checked:['Rechecked · still open','The guard checked the gate. Temporary securing is holding; the permanent repair is still needed.'],repaired:['Repair awaiting review','The guard recorded sample repair evidence. The office must review it before closure.'],closed:['Resolved','The office reviewed the sample repair evidence and approved closure.']}[value]; }
function memory() {
  const value = role === 'customer' ? state.published : state.finding;
  const [status, description] = statusFor(value);
  return heading(role === 'customer' ? 'YOUR PROPERTIES' : 'PROPERTY INTELLIGENCE','Site Memory',role === 'customer' ? 'Reviewed findings, next actions and evidence of resolution.' : 'One property. A continuous record, whoever is on patrol.') + `<div class="card"><div class="row"><div><p class="eyebrow">SAMPLE PROPERTY</p><h2>Hartwell Manor</h2></div><span class="badge blue">Guided example</span></div>${stats([[value === 'closed' ? '0':'1','Needs attention'],[value === 'repaired' ? '1':'0','Repair review'],[value === 'closed' ? '1':'0','Resolved']])}<div class="rule"></div><p class="eyebrow">EAST SIDE GATE</p><div class="row"><h2>Side gate latch needs a permanent repair</h2><span class="badge${value === 'closed' ? ' green':''}">${status}</span></div><p>${description}</p><p class="note"><strong>For the next patrol</strong><br>Check that the latch holds firmly. Record whether the repair has held and provide new inspection evidence.</p><p><small>High priority · Returned once · Responsible: Property maintenance</small></p>${role === 'customer' ? '<p class="hint">This view shows the last sample update shared by the office. Later guard checks remain private until reviewed and shared.</p>' : `<p class="hint">${state.finding === state.published ? 'The customer has this sample status.' : 'There is an unshared sample update. The customer still sees the previously reviewed status.'}</p>`}<div class="actions">${role === 'guard' ? action('Record sample recheck','recheck') + action('Record sample repair','repair',true) : role === 'admin' ? (state.finding === 'repaired' ? action('Review repair and close','close') : '') + action('Review and share update','publish') + link('Try the guard’s next check','memory','guard') : link('See the office review','memory','admin')}</div></div><section class="card spaced"><h2>Evidence and history</h2><ol class="timeline"><li><strong>Earlier patrol · finding recorded</strong><p>The latch worked loose. A temporary securing measure was recorded.</p></li><li><strong>Maintenance visit · repair reviewed</strong><p>A repair was checked and the office approved closure.</p></li><li><strong>Next patrol · problem returned</strong><p>The latch worked loose again. The issue returned to the next patrol’s briefing.</p></li>${value !== 'open' ? `<li><strong>This walkthrough · ${status}</strong><p>${description}</p></li>` : ''}</ol><p class="image-label">Illustrative history. No real customer or inspection records are used.</p></section>`;
}
function patrol() { return heading('OFFICER WORKSPACE','Today’s patrol','Dan Mercer · Sample patrol officer') + `<section class="hero"><p class="eyebrow">ON SITE · GUIDED EXAMPLE</p><h2>Hartwell Manor</h2><p>Your next check is already in the briefing: inspect the east side gate and confirm whether the latch repair holds.</p>${stats([['1','Open finding'],['2','Inspection points'],['1','Previous recurrence']])}<div class="actions">${link('Open the briefing','memory')}${link('Try Change Watch','change-watch')}</div></section><div class="card"><h2>A continuous handover</h2><p>Record a sample recheck or repair, switch to Office to review it, then open Customer to see what has been shared.</p><p class="hint">This walkthrough does not track your location, access your camera or dispatch anyone.</p></div>`; }
function customerHome() { return heading('CLIENT PORTAL','Your property, kept in view.','James Pemberton · Sample protected client') + `<section class="hero"><p class="eyebrow">HARTWELL MANOR</p><h2>Know what happened.<br>See what happens next.</h2><p>One reviewed record connects a finding, the action taken and the evidence that the issue was resolved.</p><div class="actions">${link('Open Site Memory','memory')}</div></section>`; }
const plans = {
 absence:{label:'Guard absent',title:'A reserve protects the affected patrols',gap:'3 patrols affected',cost:'£42',reserve:'55 min',steps:['The office confirms a reserve officer’s attendance, access and transport.','The prepared example moves three patrols into that reserve’s available window.','The example leaves 55 minutes for the unexpected.'],limit:'Before a real plan is used, the live app checks the actual commitments, recorded licences, travel assumptions and resources.'},
 vehicle:{label:'Vehicle unavailable',title:'Keep the officer. Replace the missing resource.',gap:'1 vehicle unavailable',cost:'£28',reserve:'40 min',steps:['The example identifies the patrols depending on the unavailable vehicle.','The office confirms a spare vehicle and its collection arrangements.','The prepared recovery preserves the patrol sequence.'],limit:'This is a prepared example. It does not check current vehicle availability or book equipment.'},
 alarms:{label:'Two alarms at once',title:'A second response needs confirmed cover',gap:'2 call-outs overlap',cost:'Needs review',reserve:'Unconfirmed',steps:['The first response can be covered in the prepared example.','The second would pull an officer away from a fixed commitment.','The example remains unresolved until a second responder is confirmed.'],limit:'An unresolved example cannot be treated as an approved response plan.'},
 delay:{label:'Guard delayed',title:'Protect the narrowest attendance window first',gap:'45-minute delay',cost:'£19',reserve:'30 min',steps:['The example flags the first patrol window as exposed.','A confirmed reserve handles the earliest attendance.','The delayed officer resumes the later sample patrols.'],limit:'The live app would recheck the whole operating period. These displayed results are prepared, not recalculated.'}
};
function planB() { const p=plans[scenario]; return heading('KEYSTONE INTELLIGENCE','Plan B','Explore prepared examples of how a disruption could be reviewed.') + '<p class="hint"><strong>Guided results:</strong> choose a scenario to inspect its example outcome. These figures are illustrative, not a calculation for your operation.</p>' + `<div class="selector" aria-label="Prepared scenarios">${Object.entries(plans).map(([id,p])=>`<button data-scenario="${id}" aria-pressed="${id===scenario}">${p.label}</button>`).join('')}</div><section class="card"><span class="prepared">PREPARED SCENARIO RESULT</span><div class="row"><h2>${p.title}</h2><span class="badge${scenario==='alarms'?'':' green'}">${scenario==='alarms'?'Unresolved example':'Illustrative recovery'}</span></div>${stats([[p.gap,'Exposure'],[p.cost,'Example extra cost'],[p.reserve,'Example reserve time']])}<ol class="timeline">${p.steps.map((s,i)=>`<li><strong>Step ${i+1}</strong><p>${s}</p></li>`).join('')}</ol><p class="note">${p.limit}</p><div class="actions">${action('Bookmark this example','bookmark-plan',true)}</div></section>`; }
const opportunities={nearby:{name:'Nearby estate patrol',distance:'4.2 km',travel:'8 min',cost:'£10.65',fee:'£45.00',contribution:'£34.35',reserve:'47 min',fit:'Fits the example round',description:'A site close to the existing sample round leaves more time available for other work.'},remote:{name:'Remote farm patrol',distance:'28 km',travel:'42 min',cost:'£30.10',fee:'£45.00',contribution:'£14.90',reserve:'13 min',fit:'Tight reserve in this example',description:'The longer diversion reduces the example contribution and leaves less spare time.'},window:{name:'Narrow attendance window',distance:'6.5 km',travel:'12 min',cost:'—',fee:'£45.00',contribution:'—',reserve:'—',fit:'Window conflicts in this example',description:'The short requested attendance window overlaps a fixed sample commitment. A different time or additional cover would need review.'}};
function growth() {const o=opportunities[opportunity];return heading('COMMERCIAL INTELLIGENCE','Growth Radar','See why the next contract’s location and service window matter.') + '<p class="hint"><strong>Prepared comparison:</strong> these fixed examples explain the feature. Entering an address or running a live quote is available in the private app.</p>' + `<div class="selector" aria-label="Sample opportunities">${Object.entries(opportunities).map(([id,p])=>`<button data-opportunity="${id}" aria-pressed="${id===opportunity}">${p.name}</button>`).join('')}</div><section class="card"><span class="prepared">ILLUSTRATIVE OPPORTUNITY · ONE 25-MINUTE PATROL</span><div class="row"><h2>${o.name}</h2><span class="badge${opportunity==='nearby'?' green':''}">${o.fit}</span></div><p>${o.description}</p>${stats([[o.cost,'Extra cost per night'],[o.contribution,'Contribution per night'],[o.reserve,'Reserve remaining']])}<div class="grid"><div><h3>Example route impact</h3><ul class="result-list"><li>Additional road distance: ${o.distance}</li><li>Additional travel: ${o.travel}</li><li>Proposed fee: ${o.fee} per night</li></ul></div><div><h3>What the office reviews</h3><ul class="result-list"><li>The requested service and attendance window.</li><li>The existing round and the people able to serve it.</li><li>Full business costs before a quote is sent.</li></ul></div></div><p class="note">Prepared figures for demonstration only. They are not generated by the private planning engine and are not pricing advice.</p>${action('Bookmark this comparison','bookmark-growth',true)}</section>`;}
function changeWatch() { return heading('PROPERTY INTELLIGENCE','Change Watch','East side gate · Hartwell Manor · Sample inspection point') + '<p class="hint">This guided example uses illustrations and a prepared highlighted region. It does not upload photographs or run the private app’s comparison workflow.</p>' + `<div class="grid"><section class="card"><h3>Approved reference</h3><div class="comparison"><img src="./reference.svg" alt="Illustrative reference showing a closed gate"></div><p class="image-label">Sample reference illustration</p></section><section class="card"><h3>Next inspection</h3><div class="comparison${highlight?' highlight':''}"><img src="./changed.svg" alt="Illustrative next inspection showing the gate open"></div><p class="image-label">Sample changed-view illustration</p></section></div><section class="card spaced"><h2>Compare. Confirm. Follow up.</h2><p>The officer reviews the visual evidence and records what they found. A highlighted difference is a prompt for human review.</p><div class="actions">${action(highlight?'Hide example highlight':'Show example highlight','highlight',true)}${action('Confirm sample change','confirm-change')}</div>${state.compared?'<p class="hint">Sample change recorded. The gate finding is ready for follow-up in Site Memory.</p>':''}<div class="actions">${link('Open linked Site Memory','memory')}</div></section>`; }
function render() {
  const view=viewName();
  $('#workspace').textContent={admin:'Operations workspace',guard:'Officer workspace',customer:'Client portal'}[role];
  $('#navigation').innerHTML=allowed.map(v=>`<a class="nav-link${view===v?' active':''}" ${view===v?'aria-current="page"':''} href="${path(v)}">${labels[v]}</a>`).join('');
  $('#personas').innerHTML=Object.entries(names).map(([id,label])=>`<a class="role-link${role===id?' active':''}" ${role===id?'aria-current="true"':''} href="${path(id==='admin'?'intelligence':id==='guard'?'patrol':'home',id)}">${label}</a>`).join('');
  $('#main').innerHTML=({intelligence:home,memory,patrol,home:customerHome,'plan-b':planB,growth,'change-watch':changeWatch}[view])();
}
function review(kind) {
  const modal=document.createElement('dialog'); const closing=kind==='close'; const [status,description]=statusFor(closing?'closed':state.finding);
  modal.innerHTML=`<h2>${closing?'Review sample repair':'Review customer update'}</h2><p>${closing?'The sample repair evidence shows the latch holding firmly. Closing this finding is separate from sharing it with the customer.':'The customer will receive this sample snapshot. Later checks remain unshared until the office reviews them.'}</p><p class="badge">${status}</p><p>${description}</p><div class="actions"><button class="button" data-confirm>${closing?'Approve sample closure':'Share reviewed sample'}</button><button class="button secondary" data-cancel>Cancel</button></div>`;
  const opener=document.activeElement;
  document.body.append(modal); modal.showModal();
  modal.querySelector('[data-cancel]').onclick=()=>modal.close();
  modal.querySelector('[data-confirm]').onclick=()=>{if(closing)state.finding='closed';else state.published=state.finding;persist();modal.close();render();notice(closing?'Sample repair closed. Share the reviewed update when ready.':'Sample snapshot shared. Switch to Customer to see it.');};
  modal.addEventListener('close',()=>{modal.remove();if(opener?.isConnected)opener.focus();});
}
document.addEventListener('click',event=>{
 const button=event.target.closest('button');if(!button)return;
 if(button.dataset.scenario){scenario=button.dataset.scenario;render();return;}
 if(button.dataset.opportunity){opportunity=button.dataset.opportunity;render();return;}
 const action=button.dataset.action;
 if(action==='recheck'||action==='repair'){state.finding=action==='repair'?'repaired':'checked';persist();render();notice('Sample check saved. Switch to Office to review it.');}
 if(action==='close'||action==='publish')review(action);
 if(action==='highlight'){highlight=!highlight;render();}
 if(action==='confirm-change'){state.compared=true;state.finding='open';persist();render();notice('Sample finding linked to Site Memory.');}
 if(action?.startsWith('bookmark-')){state[action]=action==='bookmark-plan'?scenario:opportunity;persist();notice('Example bookmarked in this browser. No live plan or quote has been created.');}
});
$('#reset').onclick=()=>{state={finding:'open',published:'open',compared:false};persist();highlight=false;render();notice('The sample walkthrough has been reset.');};
window.addEventListener('hashchange',()=>{render();$('#main').focus();window.scrollTo({top:0});});
render();
